#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from util.log import Logger
from reader import csv_reader


class StructItem:
    def __init__(self, name, field_num, repeated_num):
        self.name = name
        self.field_num = field_num
        self.repeated_num = repeated_num


class FieldItem:
    def __init__(self, name, type, details, comment):
        self.name = name
        self.type = type
        self.details = details
        self.comment = comment


class ProtoMaker:
    def __init__(self, file_path, sheet_name, all_data):
        self._file_path = file_path
        self._sheet_name = sheet_name
        self._all_data = all_data

        self._row_num = len(all_data)
        self._col_num = len(all_data[0])

        self._indentation = 0
        self._output = []  # 所有的输出

    def _GenHeadComment(self):
        self._output.append("/**")
        self._output.append(" * Generated by `ProtoMaker` (see ). DO NOT EDIT!!!")
        self._output.append(" * Source: FILE: %s, SHEET: %s" % (self._file_path, self._sheet_name))
        self._output.append(" */")


def main():
    Logger.debug("Hello, this line is for test|int:%u|double:%u|string:%s", 100, 3.14, "abc")

if __name__ == "__main__":
    main()
